# Generated by Django 5.0.4 on 2024-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "baby_number",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("age", models.PositiveIntegerField()),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("parent_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bringer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "period_of_stay",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("time_in", models.DateTimeField(max_length=50)),
                ("fee_in_ugx", models.FloatField()),
                ("taker_name", models.CharField(blank=True, max_length=50, null=True)),
                ("time_out", models.DateTimeField(max_length=50)),
                ("comment", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categorystay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(blank=True, max_length=50, null=True)),
                ("l_name", models.CharField(blank=True, max_length=50, null=True)),
                ("l_location", models.CharField(max_length=50, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("nok", models.CharField(blank=True, max_length=50, null=True)),
                ("nin", models.IntegerField(blank=True, null=True)),
                ("rec_name", models.CharField(blank=True, max_length=50, null=True)),
                ("rec_contact", models.CharField(blank=True, max_length=50, null=True)),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                ("educ_level", models.CharField(blank=True, max_length=50, null=True)),
                ("s_number", models.IntegerField(blank=True, null=True)),
                (
                    "availability_zone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("payment", models.FloatField()),
                ("s_contact", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
