# Generated by Django 5.0.4 on 2024-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baby",
            name="time_in",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="baby",
            name="time_out",
            field=models.DateTimeField(),
        ),
    ]
