# Generated by Django 5.0.4 on 2024-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0002_alter_baby_time_in_alter_baby_time_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitter",
            name="availability_zone",
        ),
        migrations.AddField(
            model_name="sitter",
            name="avail_status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Availability Status"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="educ_level",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Level of Education"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="f_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="l_location",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="l_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="nin",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="National ID Number"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="nok",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Next of Kin"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="payment",
            field=models.FloatField(verbose_name="Amount Paid to Sitter"),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="rec_contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Recommender's Contact",
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="rec_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Recommender's Name"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                    ("Hindu", "Hindu"),
                    ("Buddhist", "Buddhist"),
                    ("Jewish", "Jewish"),
                    ("Rather not say", "Rather not say"),
                ],
                max_length=50,
                null=True,
                verbose_name="Religius Affiliation",
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="s_contact",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Sitter's Contact"
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="s_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Sitter Number"
            ),
        ),
    ]
