# Generated by Django 5.0.4 on 2024-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daystarapp",
            "0003_remove_sitter_availability_zone_sitter_avail_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitter",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                    ("Hindu", "Hindu"),
                    ("Buddhist", "Buddhist"),
                    ("Jewish", "Jewish"),
                    ("Rather not say", "Rather not say"),
                ],
                max_length=50,
                null=True,
                verbose_name="Religious Affiliation",
            ),
        ),
    ]
