# Generated by Django 5.0.4 on 2024-04-24 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0004_alter_sitter_religion"),
    ]

    operations = [
        migrations.AddField(
            model_name="baby",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="daystarapp.categorystay",
            ),
        ),
        migrations.AlterField(
            model_name="categorystay",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Morning", "Morning"),
                    ("Afternoon", "Afternoon"),
                    ("Evening", "Evening"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="educ_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Certificate", "Certificate"),
                    ("Diploma", "Diploma"),
                    ("Bachelors", "Bachelors"),
                    ("Masters", "Masters"),
                ],
                max_length=50,
                null=True,
                verbose_name="Level of Education",
            ),
        ),
    ]
