# Generated by Django 5.0.4 on 2024-04-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0005_baby_category_alter_categorystay_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Babyfee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="categorystay",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Morning", "Morning"),
                    ("Afternoon", "Afternoon"),
                    ("Evening", "Evening"),
                    ("Whole Day", "Whole Day"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="avail_status",
            field=models.CharField(
                blank=True,
                choices=[("On Campus", "On Campus"), ("Off Campus", "Off Campus")],
                max_length=50,
                null=True,
                verbose_name="Availability Status",
            ),
        ),
        migrations.CreateModel(
            name="SitterPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("number_of_babies", models.IntegerField()),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "sitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.sitter",
                    ),
                ),
            ],
        ),
    ]
