# Generated by Django 5.0.4 on 2024-04-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0007_remove_baby_category_remove_babyfee_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="babyfee",
            name="name",
        ),
        migrations.AddField(
            model_name="babyfee",
            name="l_name",
            field=models.ForeignKey(
                blank=True,
                default=1,
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="daystarapp.baby",
                verbose_name="Name of baby",
            ),
            preserve_default=False,
        ),
    ]
