# Generated by Django 5.0.4 on 2024-04-24 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0008_remove_babyfee_name_babyfee_l_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Doll Name")),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Brand"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Color"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                ("qty_in_stock", models.IntegerField(verbose_name="Quantity in Stock")),
            ],
        ),
        migrations.CreateModel(
            name="Supplies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100, verbose_name="Item")),
                (
                    "qty_stocked",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Quantity Stocked"
                    ),
                ),
                ("date_stocked", models.DateField(verbose_name="Date Stocked")),
                ("qty_on_hand", models.IntegerField(verbose_name="Quantity In Stock")),
                (
                    "consumed_today",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Daily Comsumption"
                    ),
                ),
                ("qty_left", models.IntegerField(verbose_name="Quantity Left")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
            ],
        ),
        migrations.RenameField(
            model_name="baby",
            old_name="bringer_name",
            new_name="parent_contact",
        ),
        migrations.RemoveField(
            model_name="baby",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="baby",
            name="fee_in_ugx",
        ),
        migrations.RemoveField(
            model_name="baby",
            name="period_of_stay",
        ),
        migrations.RemoveField(
            model_name="baby",
            name="taker_name",
        ),
        migrations.RemoveField(
            model_name="baby",
            name="time_in",
        ),
        migrations.RemoveField(
            model_name="baby",
            name="time_out",
        ),
        migrations.RemoveField(
            model_name="babyfee",
            name="category",
        ),
        migrations.RemoveField(
            model_name="sitter",
            name="avail_status",
        ),
        migrations.RemoveField(
            model_name="sitter",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="sitterpayment",
            name="sitter",
        ),
        migrations.AddField(
            model_name="babyfee",
            name="pay_for",
            field=models.CharField(
                blank=True,
                choices=[("Half-day", "Half-day"), ("Full-day", "Full-day")],
                max_length=20,
                null=True,
                verbose_name="Pay For",
            ),
        ),
        migrations.AddField(
            model_name="sitterpayment",
            name="l_name",
            field=models.ForeignKey(
                blank=True,
                default=1,
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                to="daystarapp.sitter",
                verbose_name="Name of Sitter",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="arrival_time",
            field=models.DateTimeField(verbose_name="Time of Arrival"),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="l_name",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="daystarapp.baby",
                verbose_name="Paid For",
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Fees Paid"
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                    ("Mobile Money", "Mobile Money"),
                    ("Bank Transfer", "Bank Transfer"),
                ],
                max_length=50,
                null=True,
                verbose_name="Mode of Payment",
            ),
        ),
        migrations.CreateModel(
            name="At_school",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.DateTimeField(verbose_name="Time of Arrival")),
                (
                    "bringer_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Baby brought in by:",
                    ),
                ),
                (
                    "period_of_stay",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Morning", "Morning"),
                            ("Afternoon", "Afternoon"),
                            ("Evening", "Evening"),
                            ("Whole Day", "Whole Day"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(verbose_name="Time of Departure"),
                ),
                (
                    "taker_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Baby picked by:",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "l_name",
                    models.ForeignKey(
                        blank=True,
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.sitter",
                        verbose_name="Assigned to Sitter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DollSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Sale Date"
                    ),
                ),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quantity Sold"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Amount"
                    ),
                ),
                (
                    "doll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.doll",
                        verbose_name="Doll",
                    ),
                ),
                (
                    "l_name",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.baby",
                        verbose_name="Sold To",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="In_school",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avail_status",
                    models.CharField(
                        blank=True,
                        choices=[("On Duty", "On Duty"), ("Off Duty", "Off Duty")],
                        max_length=50,
                        null=True,
                        verbose_name="Availability Status",
                    ),
                ),
                (
                    "babies_attd",
                    models.CharField(max_length=100, verbose_name="Babies attended to"),
                ),
                ("payment", models.FloatField(verbose_name="Amount Paid to Sitter")),
                (
                    "l_name",
                    models.ForeignKey(
                        blank=True,
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.sitter",
                        verbose_name="Name of Sitter",
                    ),
                ),
            ],
        ),
    ]
