# Generated by Django 5.0.4 on 2024-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0009_doll_supplies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(
                blank=True, max_length=50, null=True, verbose_name="Payment Date"
            ),
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateTimeField(
                blank=True, max_length=50, null=True, verbose_name="Sale Date"
            ),
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(
                blank=True, max_length=50, null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="number_of_babies",
            field=models.IntegerField(verbose_name="Number of Babies Attended To"),
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount Paid to Sitter"
            ),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="date_stocked",
            field=models.DateField(
                blank=True, max_length=50, null=True, verbose_name="Date Stocked"
            ),
        ),
    ]
