# Generated by Django 5.0.4 on 2024-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daystarapp",
            "0010_alter_babyfee_payment_date_alter_dollsale_sale_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateField(blank=True, null=True, verbose_name="Sale Date"),
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="date_stocked",
            field=models.DateField(blank=True, null=True, verbose_name="Date Stocked"),
        ),
        migrations.AlterField(
            model_name="supplies",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
        ),
    ]
