# Generated by Django 5.0.4 on 2024-04-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0012_dollsale_price_alter_babyfee_departure_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Supplies",
            new_name="Supply",
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="l_name",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="daystarapp.baby",
                verbose_name="For Baby",
            ),
        ),
        migrations.AlterField(
            model_name="in_school",
            name="babies_attd",
            field=models.CharField(max_length=100, verbose_name="Babies Assigned"),
        ),
    ]
