# Generated by Django 5.0.4 on 2024-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0015_alter_babyfee_departure_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="cost_per_item",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Cost Per Item"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supply",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Total Cost"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doll",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cost",
            ),
        ),
    ]
