# Generated by Django 5.0.4 on 2024-04-30 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0016_supply_cost_per_item_supply_total_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="price",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=7,
                validators=[django.core.validators.RegexValidator(r'^[0-9]+$')],
                verbose_name="Price",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="in_school",
            name="babies_attd",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="daystarapp.baby",
                verbose_name="Babies Assigned",
            ),
        ),
    ]
