# Generated by Django 5.0.4 on 2024-04-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daystarapp",
            "0017_alter_babyfee_departure_time_alter_dollsale_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dollsale",
            name="total_amount",
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="cost_per_item",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Cost Per Item"
            ),
        ),
    ]
