# Generated by Django 5.0.4 on 2024-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0018_remove_dollsale_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dollsale",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
