# Generated by Django 5.0.4 on 2024-04-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0019_dollsale_total_amount_alter_babyfee_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="consumed_today",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Daily Comsumption"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_left",
            field=models.CharField(max_length=20, verbose_name="Quantity Left"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_on_hand",
            field=models.CharField(max_length=20, verbose_name="Quantity In Stock"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_stocked",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Quantity Stocked"
            ),
        ),
    ]
