# Generated by Django 5.0.4 on 2024-04-30 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daystarapp",
            "0021_remove_babyfee_payment_amount_babyfee_amount_due_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="amount_paid",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
