# Generated by Django 5.0.4 on 2024-05-01 10:47

import daystarapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daystarapp",
            "0025_alter_baby_baby_number_alter_babyfee_departure_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="baby",
            name="parent_contact",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="rec_contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[daystarapp.models.validate_phone_number],
                verbose_name="Recommender's Contact",
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="s_contact",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[daystarapp.models.validate_phone_number],
                verbose_name="Sitter's Contact",
            ),
        ),
    ]
