# Generated by Django 5.0.4 on 2024-05-01 12:12

import daystarapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0029_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="at_school",
            name="bringer_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_two_names],
                verbose_name="Baby brought in by:",
            ),
        ),
        migrations.AlterField(
            model_name="at_school",
            name="taker_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_two_names],
                verbose_name="Baby picked by:",
            ),
        ),
        migrations.AlterField(
            model_name="baby",
            name="parent_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_two_names],
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="nok",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_two_names],
                verbose_name="Next of Kin",
            ),
        ),
        migrations.AlterField(
            model_name="sitter",
            name="rec_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_two_names],
                verbose_name="Recommender's Name",
            ),
        ),
    ]
