# Generated by Django 5.0.4 on 2024-05-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0031_alter_babyfee_departure_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, verbose_name="Administrator's Name"
                    ),
                ),
                ("password", models.CharField(max_length=50, verbose_name="Password")),
                (
                    "confirm_password",
                    models.CharField(max_length=50, verbose_name="Confirm Password"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
