# Generated by Django 5.0.4 on 2024-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0034_remove_index_confirm_password_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Index",
            new_name="Admin_login",
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
