# Generated by Django 5.0.4 on 2024-05-03 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0036_alter_babyfee_departure_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin_login",
            name="email",
            field=models.CharField(
                default=1,
                max_length=100,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter a valid email address."
                    )
                ],
                verbose_name="Administrator's Email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
