# Generated by Django 5.0.4 on 2024-05-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0037_admin_login_email_alter_babyfee_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_login",
            name="username",
            field=models.CharField(max_length=50, verbose_name="Administrator's Name"),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
