# Generated by Django 5.0.4 on 2024-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0038_alter_admin_login_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baby",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Female", "Female"), ("Male", "Male")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
    ]
