# Generated by Django 5.0.4 on 2024-05-09 16:22

import daystarapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daystarapp",
            "0040_alter_at_school_bringer_name_alter_at_school_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="at_school",
            name="comment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="at_school",
            name="departure_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Time of Departure"
            ),
        ),
        migrations.AlterField(
            model_name="at_school",
            name="taker_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[daystarapp.models.validate_two_names],
                verbose_name="Baby picked by:",
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(null=True, verbose_name="Payment Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateField(null=True, verbose_name="Sale Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(null=True, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="date_stocked",
            field=models.DateField(null=True, verbose_name="Date Stocked"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="expiry_date",
            field=models.DateField(null=True, verbose_name="Expiry Date"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "l_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.sitter",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.categorystay",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="In_school",
        ),
    ]
