# Generated by Django 5.0.4 on 2024-05-10 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0042_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(null=True, verbose_name="Payment Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateField(null=True, verbose_name="Sale Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(null=True, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="date_stocked",
            field=models.DateField(null=True, verbose_name="Date Stocked"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="expiry_date",
            field=models.DateField(null=True, verbose_name="Expiry Date"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Monthlyfee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_for",
                    models.CharField(
                        choices=[("Half-day", "Half-day"), ("Full-day", "Full-day")],
                        max_length=20,
                        verbose_name="Pay For",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount Due",
                    ),
                ),
                (
                    "amount_paid",
                    models.CharField(
                        max_length=7,
                        validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                        verbose_name="Price",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Mobile Money", "Mobile Money"),
                            ("Bank Transfer", "Bank Transfer"),
                        ],
                        max_length=50,
                        verbose_name="Mode of Payment",
                    ),
                ),
                (
                    "l_name",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daystarapp.baby",
                        verbose_name="For Baby",
                    ),
                ),
            ],
        ),
    ]
