# Generated by Django 5.0.4 on 2024-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0046_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="babyfee",
            name="pending_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Amount Pending",
            ),
        ),
    ]
