# Generated by Django 5.0.4 on 2024-05-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0052_at_school_f_name_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="at_school",
            old_name="f_name",
            new_name="first_name",
        ),
    ]
