# Generated by Django 5.0.4 on 2024-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0064_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(null=True, verbose_name="Payment Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateField(null=True, verbose_name="Sale Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(null=True, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="consumed_today",
            field=models.CharField(max_length=20, verbose_name="Daily Comsumption"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="date_stocked",
            field=models.DateField(null=True, verbose_name="Date Stocked"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="expiry_date",
            field=models.DateField(null=True, verbose_name="Expiry Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_left",
            field=models.CharField(max_length=20, verbose_name="Quantity Left"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_on_hand",
            field=models.CharField(max_length=20, verbose_name="Quantity In Stock"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_stocked",
            field=models.CharField(max_length=20, verbose_name="Quantity Stocked"),
        ),
    ]
