# Generated by Django 5.0.4 on 2024-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0065_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doll",
            name="buying_price",
            field=models.IntegerField(default=1, verbose_name="Costing Price"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doll",
            name="qty_left",
            field=models.IntegerField(default=1, verbose_name="Quantity Left"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doll",
            name="qty_stocked",
            field=models.IntegerField(default=1, verbose_name="Quantity Stocked"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(null=True, verbose_name="Payment Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doll",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Selling Price"
            ),
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateField(null=True, verbose_name="Sale Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(null=True, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="consumed_today",
            field=models.IntegerField(verbose_name="Daily Consumption"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="date_stocked",
            field=models.DateField(null=True, verbose_name="Date Stocked"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="expiry_date",
            field=models.DateField(null=True, verbose_name="Expiry Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_left",
            field=models.IntegerField(verbose_name="Quantity Left"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_on_hand",
            field=models.IntegerField(verbose_name="Quantity In Stock"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qty_stocked",
            field=models.IntegerField(verbose_name="Quantity Stocked"),
        ),
    ]
