# Generated by Django 5.0.6 on 2024-05-21 00:17

import daystarapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daystarapp", "0079_alter_babyfee_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baby",
            name="baby_number",
            field=models.CharField(
                default=0,
                max_length=4,
                unique=True,
                validators=[
                    daystarapp.models.validate_two_digit_integer,
                    django.core.validators.RegexValidator(
                        message="Value must be a two-digit integer", regex="^\\d{1,2}$"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="departure_time",
            field=models.DateTimeField(null=True, verbose_name="Time of Departure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="babyfee",
            name="payment_date",
            field=models.DateField(null=True, verbose_name="Payment Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doll",
            name="stock_date",
            field=models.DateField(null=True, verbose_name="Stock Date"),
        ),
        migrations.AlterField(
            model_name="dollsale",
            name="sale_date",
            field=models.DateField(null=True, verbose_name="Sale Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitter",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitterpayment",
            name="attendance_date",
            field=models.DateField(null=True, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="date_of_today",
            field=models.DateField(null=True, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supply",
            name="expiry_date",
            field=models.DateField(null=True, verbose_name="Expiry Date"),
            preserve_default=False,
        ),
    ]
